### ISSUE TITLE
Rounded values

### ISSUE THREAD

**Issue by DemGrg** [pbiecek/breakDown#8]
Somehow now the values given by the broken function are always rounded vs exactv (tested lm model):

f.e.
                      contribution
(Intercept)                                   2300
tenure = 3                                 -1900
MonthlyCharges = 74.4               350
SeniorCitizen = 0                           14
final_prognosis                          **720**
baseline:  0 

while:  predict(model, data_in_test[analysed_user,]) gives **721.206**

**Comment by pbiecek** [comment]
This is because `signif(digits=2)` function was used for rounding.
But I agree that it can be misleading, in the latest version both print() and plot() functions have additional arguments `digits` and `rounding_function` so user may request a specific behaviour. And by default it's `round(digits=3)`.

**Comment by pbiecek** [comment]
Here: https://pbiecek.github.io/breakDown/articles/break_lm.html you can find some examples how to use both arguments

**Comment by DemGrg** [comment]
excellent, thank you....
works great now
